source 'https://supermarket.chef.io'

metadata

cookbook 'formatron_elasticsearch', git: 'https://github.com/formatron/elasticsearch-cookbook.git'
cookbook 'formatron_beats', git: 'https://github.com/formatron/beats-cookbook.git'
cookbook 'formatron_packetbeat', git: 'https://github.com/formatron/packetbeat-cookbook.git'
cookbook 'formatron_topbeat', git: 'https://github.com/formatron/topbeat-cookbook.git'
cookbook 'formatron_filebeat', git: 'https://github.com/formatron/filebeat-cookbook.git'
cookbook 'formatron_sensu', git: 'https://github.com/formatron/sensu-cookbook.git'
cookbook 'formatron_common', git: 'https://github.com/formatron/common-cookbook.git'
